version: 0.0
os: linux
dist: focal  # Ubuntu 20.04 codename

files:
  - source: /index.html
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies_ubuntu.sh  # Adjust the script name
      timeout: 300
      runas: root
    - location: scripts/start_server.sh  # Adjust the script name
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh  # Adjust the script name
      timeout: 300
      runas: root

